name: My First Workflow
on:
    push:
        branches:
        - master
jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Print Hello World
            run: echo "Hello World! This is my first GitHub Action workflow."

  